version: '3.8'
services:
  db:
    image: postgres:15.6
    restart: always
    container_name: db
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./scripts/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}

volumes:
  postgres:
